name: cbor unittest
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup Python 3.10.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4

      - name: run unittest
        run: python3 -m unittest ./tests/test_*
